server:
  port: 9002

spring:
  application:
    name: DEPARTMENT-SERVICE

  cloud:
    config:
      enabled: true
      uri: http://localhost:9296

  datasource:
    url: jdbc:postgresql://localhost:5432/department_service
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost