server:
  port: 9001


spring:
  application:
    name: USER-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/user_service
    username: root
    password: dogood1!

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  jooq:
    sql-dialect: org.hibernate.dialect.MySQL5Dialect

  cloud:
    config:
      enabled: true
      uri: http://localhost:9296


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost