server:
  port: 9001


spring:
  application:
    name: USER-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/user_service
    username: root
    password: dogood1!

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  jooq:
    sql-dialect: org.hibernate.dialect.MySQL5Dialect
