server:
  port: 9002

#MySql Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_service
    username: root
    password: dogood1!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  jooq:
    sql-dialect: org.hibernate.dialect.MySQL5Dialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: http://localhost:8761/eureka/